services:
  oci-puller:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/chisaato/oci-puller:main
    restart: always
    environment:
      - OCI_LOG_LEVEL=debug
    volumes:
      - ./config.yaml:/config.yaml:ro
      - ./data:/data
    ports:
      - "9800:9800"
